force-app/main/default/objects/Centro__c/Centro__c.object-meta.xml
<CustomObject>
    <label>Centro</label>
    <nameField>
        <label>Centro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad__c/Disponibilidad__c.object-meta.xml
<CustomObject>
    <label>Disponibilidad</label>
    <nameField>
        <label>Disponibilidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disponibilidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Disponibilidad__c/fields/Especialidad__c.field-meta.xml
<CustomField>
    <fullName>Especialidad__c</fullName>
    <label>Especialidad</label>
    <referenceTo>Especialidad__c</referenceTo>
    <relationshipLabel>Disponibilidades</relationshipLabel>
    <relationshipName>Disponibilidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Disponibilidad__c/fields/Fecha_fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_fin__c</fullName>
    <label>Fecha fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Especialidad__c/Especialidad__c.object-meta.xml
<CustomObject>
    <label>Especialidad</label>
    <nameField>
        <label>Especialidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Especialidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Especialidad__c/fields/Centro__c.field-meta.xml
<CustomField>
    <fullName>Centro__c</fullName>
    <label>Centro</label>
    <referenceTo>Centro__c</referenceTo>
    <relationshipLabel>Especialidades</relationshipLabel>
    <relationshipName>Especialidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hueco__c/Hueco__c.object-meta.xml
<CustomObject>
    <label>Hueco</label>
    <nameField>
        <displayFormat>HN-{00000}</displayFormat>
        <label>Hueco numero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Huecos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hueco__c/fields/Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>Disponibilidad__c</fullName>
    <label>Disponibilidad</label>
    <referenceTo>Disponibilidad__c</referenceTo>
    <relationshipLabel>Huecos</relationshipLabel>
    <relationshipName>Huecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hueco__c/fields/Hora_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Hora_de_inicio__c</fullName>
    <label>Hora de inicio</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Hueco__c/fields/Hora_fin__c.field-meta.xml
<CustomField>
    <fullName>Hora_fin__c</fullName>
    <label>Hora fin</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Hueco__c/fields/Resumen_Hueco__c.field-meta.xml
<CustomField>
    <fullName>Resumen_Hueco__c</fullName>
    <description>Vanguard</description>
    <formula>CASE(
MOD( Fecha__c - DATE( 1900, 1, 8 ), 7 ),
0, &quot;Lunes&quot;,
1, &quot;Martes&quot;,
2, &quot;Miércoles&quot;,
3, &quot;Jueves&quot;,
4, &quot;Viernes&quot;,
5, &quot;Sábado&quot;,
&quot;Domingo&quot;
)

&amp; &quot; &quot; &amp; TEXT(DAY(Fecha__c)) &amp; &quot; de &quot; &amp; 

CASE(MONTH(Fecha__c),
1, &quot;Enero&quot;,
2, &quot;Febrero&quot;,
3, &quot;Marzo&quot;, 
4, &quot;Abril&quot;, 
5, &quot;Mayo&quot;, 
6, &quot;Junio&quot;,
7, &quot;Julio&quot;,
8, &quot;Agosto&quot;,
9, &quot;Septiembre&quot;,
10, &quot;Octubre&quot;,
11, &quot;Noviembre&quot;,
12, &quot;Diciembre&quot;,
&quot;Ninguno&quot;) 

 &amp; &quot;, de &quot; &amp; TRIM(LEFT(TEXT(Hora_de_inicio__c), 5)) &amp; &quot; a &quot; &amp; TRIM(LEFT(TEXT(Hora_fin__c), 5)) &amp; &quot; h&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resumen Hueco</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getApexData.cls
public with sharing class getApexData {
    @AuraEnabled
    public static List<Centro__c> getCentros(){
        return [Select Id, Name From Centro__c Order By Name Asc Limit 100];
    }

    @AuraEnabled
    public static List<Especialidad__c> getEspecialidades(String centroId){
        return [Select Id, Name From Especialidad__c Where Centro__r.Id = :centroId Order By Name Asc Limit 100];
    }

    @AuraEnabled
    public static List<Disponibilidad__c> getDisponibilidades(String especialidadId){
        Date todaysDate = System.today();
        return [
            Select Id, Fecha_de_inicio__c, Fecha_fin__c 
            From Disponibilidad__c 
            Where Especialidad__r.Id = :especialidadId AND Fecha_fin__c >= :todaysDate 
            Order By Fecha_fin__c Desc
            Limit 100
        ];
    }

    @AuraEnabled
    public static List<Hueco__c> getHuecos(Date fechaSeleccionada, String espId) {
        Date todaysDate = System.today();
        Date fechaJs = fechaSeleccionada;
        Date abanicoFechasLow = fechaJs - 4;
        Date abanicoFechasUp = fechaJs + 4;
        return [
            Select Id, Fecha__c, Name, Hora_de_inicio__c, Hora_fin__c, Resumen_Hueco__c 
            From Hueco__c 
            Where Disponibilidad__r.Especialidad__r.Id = :espId
                AND Disponibilidad__r.Fecha_fin__c >= :todaysDate
                AND Fecha__c >= :todaysDate
                AND (Fecha__c >= :abanicoFechasLow AND Fecha__c <= :abanicoFechasUp)
            Order By Fecha__c Asc
            Limit 100
        ];
    }

    @AuraEnabled
    public static List<Contact> getContact(String email, String phone){
        return [
            Select Id, Name, Phone 
            From Contact 
            Where Email = :email OR Phone = :phone
            Limit 1
        ];
    }
}